# Generated by Django 4.2.15 on 2024-11-20 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_drawn', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DrawResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.CharField(max_length=36, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('drawn_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draw.familyname')),
            ],
        ),
    ]
