# Generated by Django 4.2.15 on 2024-11-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0002_participant_result_rename_is_drawn_familyname_drawn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyname',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
