# Generated by Django 4.2.15 on 2024-11-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0003_familyname_is_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyname',
            name='drawn',
        ),
        migrations.AddField(
            model_name='familyname',
            name='unique_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='familyname',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
