# Generated by Django 4.2.15 on 2024-11-20 19:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0004_remove_familyname_drawn_familyname_unique_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyname',
            name='unique_link',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
