# Generated by Django 4.2.15 on 2024-11-22 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0005_alter_familyname_unique_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawnFamilyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawn_name', models.CharField(max_length=255)),
                ('guest_id', models.CharField(blank=True, max_length=36, null=True)),
                ('drawn_at', models.DateTimeField(auto_now_add=True)),
                ('family_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draw.familyname')),
            ],
        ),
    ]
