# Generated by Django 4.2.15 on 2024-10-12 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_related_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_user_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.user'),
        ),
    ]
