# Generated by Django 4.2.15 on 2024-10-12 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_guest_user_id_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.shippingaddress'),
            preserve_default=False,
        ),
    ]
