# Generated by Django 4.2.15 on 2024-10-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_shippingaddress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('recorded', 'Rögzített'), ('processing', 'Feldolgozás alatt'), ('shipping', 'Szállítás alatt'), ('ready_for_pickup', 'Átvehető')], default='recorded', max_length=20),
        ),
    ]
