# Generated by Django 4.2.15 on 2024-10-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_shippingaddress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Bankkártya'), ('paypal', 'PayPal'), ('bank_transfer', 'Banki átutalás'), ('cash_on_delivery', 'Utánvétes')], default='credit_card', max_length=20),
        ),
    ]
