# Generated by Django 4.2.15 on 2024-10-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_city',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_country',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_first_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_last_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_phone',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_postal_code',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='shop.product'),
        ),
    ]
