# Generated by Django 4.2.15 on 2024-10-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_billing_address_order_billing_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
