# Generated by Django 4.2.15 on 2024-10-15 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_order_billing_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
