# Generated by Django 4.2.15 on 2024-11-11 16:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_order_company_name_order_is_company_order_tax_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='barion_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='barion_status',
            field=models.CharField(choices=[('Prepared', 'Prepared'), ('Started', 'Started'), ('InProgress', 'InProgress'), ('Canceled', 'Canceled'), ('Expired', 'Expired'), ('Succeeded', 'Succeeded')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Bankkártya'), ('bank_transfer', 'Banki átutalás'), ('cash_on_delivery', 'Utánvétes')], default='credit_card', max_length=20),
        ),
    ]
