# Generated by Django 4.2.15 on 2025-01-26 18:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_order_shipping_method_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(default=2),
            preserve_default=False,
        ),
    ]
