# Generated by Django 4.2.15 on 2025-02-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_product_is_active_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
