# Generated by Django 4.2.15 on 2025-02-02 16:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_product_options_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Leírás'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sort_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Rövid leírás'),
        ),
    ]
