# Generated by Django 4.2.15 on 2025-02-02 16:47

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Leírás'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Kép'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Név'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Frissítve'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Kép'),
        ),
    ]
