# Generated by Django 4.2.15 on 2025-02-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_category_created_at_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address_line1',
            field=models.CharField(max_length=255, verbose_name='Cím1'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cím2'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Város'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Ország'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Telefonszám'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='Irányitószám'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='recipient_name',
            field=models.CharField(max_length=100, verbose_name='Név'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(max_length=100, verbose_name='Utca'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Frissítve'),
        ),
    ]
