# Generated by Django 4.2.15 on 2025-02-02 17:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_shippingaddress_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='barion_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Barion azonositó'),
        ),
        migrations.AlterField(
            model_name='order',
            name='barion_status',
            field=models.CharField(choices=[('Prepared', 'Prepared'), ('Started', 'Started'), ('InProgress', 'InProgress'), ('Canceled', 'Canceled'), ('Expired', 'Expired'), ('Succeeded', 'Succeeded')], default=None, max_length=20, null=True, verbose_name='Barion Státusz'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.CharField(default='N/A', max_length=255, verbose_name='Cím'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_city',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Város'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_country',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Ország'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_first_name',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Keresztnév'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_last_name',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Vezetéknév'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_phone',
            field=models.CharField(default='N/A', max_length=15, verbose_name='Telefonszám'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_postal_code',
            field=models.CharField(default='N/A', max_length=10, verbose_name='Írányitószám'),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='Kód'),
        ),
        migrations.AlterField(
            model_name='order',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cég náv'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva'),
        ),
        migrations.AlterField(
            model_name='order',
            name='guest_user_id',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Vendégfelhasználó azonosító'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_company',
            field=models.BooleanField(default=False, verbose_name='Céges'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Rendelés ideje'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payed',
            field=models.BooleanField(default=False, verbose_name='Fizetve'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Bankkártya'), ('bank_transfer', 'Banki átutalás'), ('cash_on_delivery', 'Utánvétes')], default='credit_card', max_length=20, verbose_name='Fizetési mód'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('store_pickup', 'Boltban történő átvétel'), ('home_delivery', 'Házhoz szállítás Szegeden'), ('free_shipping', 'Ingyenes szállítás Szegeden belül')], default='store_pickup', max_length=20, verbose_name='Szállítási mód'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('recorded', 'Rögzített'), ('processing', 'Feldolgozás alatt'), ('shipping', 'Szállítás alatt'), ('ready_for_pickup', 'Átvehető')], default='recorded', max_length=20, verbose_name='Státusz'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Adószám'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Teljes összeg'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Frissítve'),
        ),
    ]
